version: '2'

services:
  influxdb:
    image: influxdb:1.8.3
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb

  telegraf:
    image: telegraf:1.16.3
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    links:
      - influxdb:influxdb

volumes:
  chronograf_data:
  influxdb_data:
  kapacitor_data:
    
